### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by skohli0302** [yongkangchen/atom-ctags#56]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.166.0-31170dc
**System**: linux 3.13.0-24-generic
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v2.5.5

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /usr/share/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

TypeError: Cannot read property 'length' of undefined
  at /home/nic/.atom/packages/atom-ctags/lib/ctags-complete.coffee:22:9
  at /usr/share/atom/resources/app/src/workspace.js:273:16
  at /usr/share/atom/resources/app/src/workspace.js:330:18
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app/src/pane-container.js:379:27)
  at /usr/share/atom/resources/app/src/pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:334:20)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:313:14)
  at /usr/share/atom/resources/app/src/workspace.js:497:16
  at _fulfilled (/usr/share/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /usr/share/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:557:44
  at flush (/usr/share/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)

```

### Commands

```
 44x -33:31.3 core:move-down (input.hidden-input)
  2x -32:11.2 core:page-down (input.hidden-input)
     -32:10.0 core:page-up (input.hidden-input)
  3x -32:09.0 core:page-down (input.hidden-input)
     -30:03.1 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -30:00.0 core:confirm (input.hidden-input)
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.5.5
autocomplete-plus, v2.0.2
language-ejs, v0.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by bdvholmes** [comment]
https://github.com/yongkangchen/atom-ctags/blob/v2.5.5/lib/ctags-complete.coffee#L22

Appears to be the line in question

**Comment by yongkangchen** [comment]
Should be fixed as #57

**Comment by noseglid** [comment]
Still getting this issue.

[Enter steps to reproduce below:]

1. Follow a tag by 'ctrl-alt-down'

**Atom Version**: 0.179.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v2.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /opt/atom/resources/app/node_modules/q/q.js:128

TypeError: Cannot read property 'length' of undefined
  at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:391:29)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:943:53)
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/opt/atom/resources/app/src/display-buffer.js:1009:27)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToBufferPosition (/opt/atom/resources/app/src/display-buffer.js:661:47)
  at TextEditor.module.exports.TextEditor.scrollToBufferPosition (/opt/atom/resources/app/src/text-editor.js:2693:33)
  at TextEditorView.module.exports.TextEditorView.scrollToBufferPosition (/opt/atom/resources/app/src/text-editor-view.js:224:25)
  at FileView.module.exports.SymbolsView.moveToPosition (/home/alexo/.atom/packages/atom-ctags/lib/symbols-view.coffee:54:18)
  at /home/alexo/.atom/packages/atom-ctags/lib/symbols-view.coffee:47:8
  at _fulfilled (/opt/atom/resources/app/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/opt/atom/resources/app/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/opt/atom/resources/app/node_modules/q/q.js:756:13)
  at /opt/atom/resources/app/node_modules/q/q.js:564:44
  at flush (/opt/atom/resources/app/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:364:11)

```

### Commands

```
     -1:28.4 core:move-left (atom-text-editor.editor)
  2x -1:28.1 core:move-down (atom-text-editor.editor)
  2x -1:27.6 core:move-left (atom-text-editor.editor)
     -1:26.4 core:backspace (atom-text-editor.editor)
     -1:26.1 core:move-up (atom-text-editor.editor)
     -1:25.7 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -1:25.3 editor:delete-to-beginning-of-word (atom-text-editor.editor)
     -1:24.8 core:backspace (atom-text-editor.editor)
     -1:24.5 core:move-up (atom-text-editor.editor)
     -1:24.2 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -1:23.9 editor:newline (atom-text-editor.editor)
     -1:18.4 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -1:16.9 core:confirm (atom-text-editor.editor.mini)
     -1:10.8 atom-ctags:go-to-declaration (atom-text-editor.editor)
     -0:02.3 atom-ctags:return-from-declaration (atom-text-editor.editor)
     -0:00.8 atom-ctags:go-to-declaration (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tabs",
      "image-view",
      "tree-view",
      "autocomplete",
      "symbols-view"
    ],
    "themes": [
      "unity-ui",
      "unity-dark-syntax"
    ]
  },
  "atom-ctags": {
    "cmdArgs": "--exclude=node_modules --exclude=submodules",
    "extraTagFiles": "/home/alexo/devel/avhs-portal-c/avhs/portal/tags"
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.6.0
atom-ternjs, v0.4.18
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.6
build, v0.23.4
highlight-selected, v0.9.0
language-actionscript, v0.1.0
linter, v0.11.1
linter-jscs, v1.5.0
linter-jshint, v0.1.0
linter-php, v0.0.11
minimap, v4.2.2
minimap-git-diff, v3.1.1
minimap-highlight-selected, v4.0.0
sublime-tabs, v0.4.8
unity-dark-syntax, v0.1.4
unity-ui, v2.0.2

# Dev
No dev packages
```
