### ISSUE TITLE
Doesn't work on Windows 7

### ISSUE THREAD

**Issue by helarqjsc** [yongkangchen/atom-ctags#84]
When I run `Atom Ctags: Rebuild` I get the following errors:

```
please create a new issue:
command: @C:\Users\shi\.atom\packages\atom-ctags\vendor\ctags-win32 --options=C:\Users\shi\.atom\packages\atom-ctags\lib\.ctags --fields=+KSn --excmd=p -R -f - C:\xampp\htdocs\tidy-front-end\tidyApplication@failed to parseTagLine: @"ctags-win32: Warning: C:\\xampp\\htdocs\\tidy-front-end\\tidyApplication\\gulpfile.js:19: null expansion of name pattern \"\\3\"\r"@
failed to parseTagLine: @"ctags-win32: Warning: C:\\xampp\\htdocs\\tidy-front-end\\tidyApplication\\gulpfile.js:36: null expansion of name pattern \"\\3\"\r"@
failed to parseTagLine: @"ctags-win32: Warning: C:\\xampp\\htdocs\\tidy-front-end\\tidyApplication\\gulpfile.js:40: null expansion of name pattern \"\\3\"\r"@
failed to parseTagLine: @"ctags-win32: Warning: C:\\xampp\\htdocs\\tidy-front-end\\tidyApplication\\gulpfile.js:42: null expansion of name pattern \"\\3\"\r"@
failed to parseTagLine: @"ctags-win32: Warning: C:\\xampp\\htdocs\\tidy-front-end\\tidyApplication\\gulpfile.js:47: null expansion of name pattern \"\\3\"\r"@
failed to parseTagLine: @"ctags-win32: Warning: C:\\xampp\\htdocs\\tidy-front-end\\tidyApplication\\gulpfile.js:52: null expansion of name pattern \"\\3\"\r"@
failed to parseTagLine: @"ctags-win32: Warning: C:\\xampp\\htdocs\\tidy-front-end\\tidyApplication\\gulpfile.js:58: null expansion of name pattern \"\\3\"\r"@
```
gulpfile.js: http://pastebin.com/MCNagxVm

I don't see anything special on lines 36, 40, 42, etc. What is the problem? What does "null expansion of name pattern \"\\3\"\r"@" mean and how can this be solved?

**Comment by yongkangchen** [comment]
Should be fixed in latest version

**Comment by helarqjsc** [comment]
I'm using atom-ctags 3.2.0 and Atom 0.200.0. Still getting this error.

**Comment by yongkangchen** [comment]
I guess there something wrong with the javascript ctag rules.
You can search: https://www.google.com.hk/#safe=strict&q=ctags+javascript+rule
find the best rules for javascript and add it to `$HOME/ctags.cnf (on MSDOS, MSWindows only) `

**Comment by yongkangchen** [comment]
Or you can just ignore the error :)
